#index:
#    path: /
#    controller: App\Controller\DefaultController::index
creationuser:
  path: /creationuser
  controller: App\Controller\AuthController::creationuser
  methods: POST

login_check:
  path: /login_check
  methods: [POST]

connexion:
  path: /connexion_check
  methods: [POST]


swagger_ui:
  path: /docs
  controller: api_platform.swagger.action.ui

api_graphql_entrypoint:
  path: /api/graphql
  controller: api_platform.graphql.action.entrypoint
